const grid=document.querySelector('#productGrid'),filters=document.querySelector('#filters'),search=document.querySelector('#searchInput'),empty=document.querySelector('#emptyState'),resultCount=document.querySelector('#resultCount');
const categories=[['special','推荐'],['all','全部'],['toast','吐司'],['jianshui','碱水'],['oubao','欧包'],['rice','米面包'],['cakebox','蛋糕盒'],['other','其他']];
let active='special';
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
filters.innerHTML=categories.map(([id,label])=>`<button class="filter-btn ${id===active?'active':''}" data-filter="${id}">${label}</button>`).join('');
function matchesCategory(p){if(active==='all')return true;if(active==='other')return !['toast','jianshui','oubao','rice','cakebox'].some(x=>p.category.includes(x));return p.category.includes(active)}
function render(){const q=search.value.trim().toLowerCase();const shown=PRODUCTS.filter(p=>matchesCategory(p)&&(!q||`${p.name} ${p.keywords} ${p.tag}`.toLowerCase().includes(q)));resultCount.textContent=`${shown.length} 款`;empty.hidden=shown.length>0;grid.hidden=!shown.length;grid.innerHTML=shown.map(p=>`<article class="product-card"><div class="product-image"><img src="images-styled/${encodeURI(p.image)}" alt="${safe(p.name)}" loading="lazy">${p.category.includes('special')?'<span class="special-badge">小鸭推荐</span>':''}</div><div class="product-body"><div class="product-top"><h3>${safe(p.name)}</h3><span class="tag">${safe(p.tag)}</span></div><p class="description">${safe(p.description||'今日新鲜制作')}</p><div class="product-bottom"><span class="price">${safe(p.price)}</span><button class="add-btn" data-add="${safe(p.name)}" aria-label="将 ${safe(p.name)} 加入购物袋">＋</button></div></div></article>`).join('')}
filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;active=b.dataset.filter;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()});
search.addEventListener('input',()=>{if(search.value&&active!=='all'){active='all';filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'))}render()});
let cart=(()=>{try{return JSON.parse(localStorage.getItem('duck_bakery_cart_v1'))||{}}catch{return{}}})();
const drawer=document.querySelector('#cartDrawer'),mask=document.querySelector('#drawerMask'),items=document.querySelector('#cartItems'),count=document.querySelector('#cartCount'),total=document.querySelector('#cartTotal'),toast=document.querySelector('#toast');
function save(){localStorage.setItem('duck_bakery_cart_v1',JSON.stringify(cart))}function amount(){return Object.values(cart).reduce((a,b)=>a+b,0)}
function renderCart(){const entries=Object.entries(cart);const n=amount();count.textContent=total.textContent=n;items.innerHTML=entries.length?entries.map(([name,qty])=>`<div class="cart-row"><p>${safe(name)}</p><div class="qty"><button data-name="${safe(name)}" data-delta="-1">−</button><span>${qty}</span><button data-name="${safe(name)}" data-delta="1">＋</button></div><button class="remove" data-remove="${safe(name)}">移除</button></div>`).join(''):'<div class="cart-empty">购物袋还是空的<br>去挑一只喜欢的面包吧 🥐</div>'}
function notify(text){toast.textContent=text;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1300)}
function openCart(on=true){drawer.classList.toggle('open',on);drawer.setAttribute('aria-hidden',String(!on));mask.hidden=!on;document.body.style.overflow=on?'hidden':''}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(!b)return;cart[b.dataset.add]=(cart[b.dataset.add]||0)+1;save();renderCart();notify('已放进购物袋 ♡')});
items.addEventListener('click',e=>{const d=e.target.dataset;if(d.remove)delete cart[d.remove];if(d.delta){cart[d.name]=(cart[d.name]||0)+Number(d.delta);if(cart[d.name]<1)delete cart[d.name]}save();renderCart()});
document.querySelector('#cartOpen').onclick=()=>openCart();document.querySelector('#cartClose').onclick=()=>openCart(false);mask.onclick=()=>openCart(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')openCart(false)});document.querySelector('#cartClear').onclick=()=>{cart={};save();renderCart()};
document.querySelector('#cartCopy').onclick=async()=>{const text=Object.entries(cart).length?['Duck Bakery 订购清单','',...Object.entries(cart).map(([n,q])=>`${n} × ${q}`)].join('\n'):'购物清单为空';try{await navigator.clipboard.writeText(text);notify('清单已复制，可以发给店主啦')}catch{prompt('复制下面的订购清单：',text)}};
render();renderCart();
